# Generated by Django 4.2.1 on 2023-06-02 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-publish'], 'verbose_name_plural': 'Tests'},
        ),
        migrations.RenameField(
            model_name='test',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='test',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2),
        ),
        migrations.AddField(
            model_name='test',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='prog_language',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('HTML', 'HTML')], default='PY', max_length=4),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['-publish'], name='tests_test_publish_6033f4_idx'),
        ),
    ]
