# Generated by Django 4.2 on 2023-07-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_alter_test_prog_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="prog_language",
            field=models.CharField(
                choices=[
                    ("PY", "Python"),
                    ("JS", "JavaScript"),
                    ("HTML", "HTML"),
                    ("SQL", "SQL"),
                    ("PHP", "PHP"),
                    ("C", "C"),
                    ("CPP", "C++"),
                ],
                default="PY",
                max_length=4,
                verbose_name="Programming language",
            ),
        ),
    ]
