# Generated by Django 4.2.1 on 2023-06-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_options_rename_created_at_test_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question'], 'verbose_name_plural': 'Answers'},
        ),
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('SC', 'single choice'), ('MC', 'multiple choice'), ('WR', 'write in')], default='SC', max_length=2, verbose_name='Answer type'),
        ),
    ]
