# Generated by Django 4.2.1 on 2023-06-07 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_answer_options_test_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='experience',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='prog_language',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('HTML', 'HTML')], default='PY', max_length=4, verbose_name='Programming language'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2, verbose_name='Test status'),
        ),
    ]
