# Generated by Django 4.2.1 on 2023-06-07 17:08

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('tests', '0004_alter_test_experience_alter_test_prog_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='test',
            name='prog_language',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('HTML', 'HTML'), ('SQL', 'SQL')], default='PY', max_length=4, verbose_name='Programming language'),
        ),
    ]
