# Generated by Django 4.2.3 on 2023-07-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_result_pass_date_result_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='login',
            field=models.BooleanField(default=False),
        ),
    ]
