# Generated by Django 4.2.1 on 2023-06-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_test_tags_alter_test_prog_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='tests.question')),
            ],
            options={
                'verbose_name_plural': 'Codes',
                'ordering': ['question'],
            },
        ),
    ]
