# Generated by Django 4.2.1 on 2023-06-29 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_code_text_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='times_taken',
        ),
        migrations.AddField(
            model_name='test',
            name='score_to_pass',
            field=models.PositiveSmallIntegerField(default=80, help_text='score in percentages', validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Required score to pass'),
        ),
        migrations.AlterField(
            model_name='test',
            name='experience',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=3)]),
        ),
    ]
