# Generated by Django 4.2 on 2023-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="date_of_birth",),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="", max_length=256),
        ),
    ]
