# Generated by Django 4.2.1 on 2023-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('positive_rate', models.PositiveSmallIntegerField(default=0)),
                ('rate_count', models.PositiveSmallIntegerField(default=0)),
                ('solved', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(null=True)),
                ('tags', models.TextField(null=True)),
                ('languages', models.TextField(null=True)),
            ],
        ),
    ]
