# Generated by Django 4.2.3 on 2023-07-06 15:02

from tasks.models import tasks_tests_directory_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='test_file',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_language', models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('HTML', 'HTML'), ('SQL', 'SQL'), ('PHP', 'PHP')], default='PY', max_length=4, verbose_name='Programming language')),
                ('test_file', models.FileField(blank=True, default=None, null=True, upload_to=tasks_tests_directory_path)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='tasks.tasks')),
            ],
        ),
    ]
