# Generated by Django 4.2.1 on 2023-05-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['create_datetime'], 'verbose_name': 'Tasks', 'verbose_name_plural': 'Tasks'},
        ),
    ]
