# Generated by Django 4.2.3 on 2023-07-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_tasks_languages_remove_tasks_test_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklanguage',
            name='prog_language',
            field=models.CharField(blank=True, choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('HTML', 'HTML'), ('SQL', 'SQL'), ('PHP', 'PHP')], default=None, max_length=4, verbose_name='Programming language'),
        ),
    ]
