# Generated by Django 4.2.3 on 2023-07-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasklanguage_prog_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
