# Generated by Django 4.2.3 on 2023-07-08 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_result_date_alter_result_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
