# Generated by Django 4.2.3 on 2023-07-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklanguage',
            name='prog_language',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('HTML', 'HTML'), ('SQL', 'SQL'), ('PHP', 'PHP')], default=None, max_length=4, verbose_name='Programming language'),
        ),
        migrations.AddConstraint(
            model_name='tasklanguage',
            constraint=models.UniqueConstraint(fields=('task', 'prog_language'), name='unique_language'),
        ),
    ]
