# Generated by Django 4.2 on 2023-07-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_result_prog_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklanguage",
            name="prog_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PY", "Python"),
                    ("JS", "JavaScript"),
                    ("HTML", "HTML"),
                    ("SQL", "SQL"),
                    ("PHP", "PHP"),
                ],
                default=None,
                max_length=4,
                null=True,
                verbose_name="Programming language",
            ),
        ),
    ]
