# Generated by Django 4.2 on 2023-07-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_alter_tasklanguage_prog_language_and_more"),
        ("tasks", "0013_alter_result_unique_together"),
    ]

    operations = []
